# STM32 application builder
#
# Author: Marcelo Barros de Almeida <marcelobarrosalmeida@gmail.com>
# License: BSD
# 

include ../globals.inc
include sources.inc

# outputs
STATICLIB:=../$(G_BLDDIR)/libstm32f4.a
G_INCS:=$(G_INCS) -I../$(APP)/include
EXEC=

# sources
G_SRCDIR=Src
include ../makefile.inc

